# Generated by Django 4.1.1 on 2022-09-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='имя')),
                ('number', models.IntegerField(verbose_name='число')),
                ('is_activated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'временная модель',
                'verbose_name_plural': 'временные модели',
                'ordering': ('number',),
            },
        ),
    ]
